In [2]:
!pip install numpy
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print()

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print()

arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3)
print()

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]



In [4]:
a1 = np.zeros((2, 3))
print(a1)
print()

a2 = np.ones((2, 3))
print(a2)
print()

a3 = np.ones_like(arr3)
print(a3)
print()

full_arr = np.full((2, 3), 5)
print(full_arr)
print()

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]

[[5 5 5]
 [5 5 5]]



In [5]:
a4 = np.eye(3)
print(a4)
print()

a5 = np.eye(3, 4)
print(a5)
print()

a6 = np.eye(3, 4, k=1)
print(a6)
print()

a7 = np.eye(3, 4, k=-1)
print(a7)
print()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]



In [6]:
# 1이상 10 미만까지 2간격으로 수의 배열을 생성(range의 배열 버전)
a = np.arange(1, 10, 2)
print(a)
print()

# 0부터 10까지 균등한 간격으로 5개 숫자 배열 생성(endpoint=True라서 10을 포함, retstep=True라서 끝에 간격을 표시해줌)
b = np.linspace(0, 10, 5, endpoint=True, retstep=True)
print(b)
print()

# logspace는 linspace랑 똑같은데 대신 log값을 씀
c = np.log10(100)
print(c)
c = np.logspace(np.log10(10), np.log10(100), num=5)
print(c)

[1 3 5 7 9]

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)

2.0
[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [7]:
# 0부터 1까지 랜덤한 숫자 생성
np.random.seed()
a = np.random.random(10)
print(a)
print()

# 시드란? 랜덤값을 정하는 씨앗값. 씨앗값이 정해지면 난수가 고정이 됨
np.random.seed(0)
a = np.random.random(10)
print(a)
b = np.random.randint(1, 10, (2, 3))    # 정수로 랜덤값 생성
print(b)
c = np.random.rand(2, 3)    # 균등분포 함수임
print(c)
d = np.random.randn(2, 3)   # 정규분포 함수임
print(d)

[0.34125382 0.54195337 0.48209813 0.08825253 0.66103383 0.06279275
 0.43659955 0.33652771 0.80037882 0.74152675]

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
[[7 8 8]
 [9 2 6]]
[[0.83607876 0.33739616 0.64817187]
 [0.36824154 0.95715516 0.14035078]]
[[-0.07770457  1.08963016  0.09654267]
 [ 1.41866711  1.16827314  0.94718595]]


In [8]:
# 배열 속성

arr = np.arange(1, 6)
print(arr)  # 배열
print("ndim: ", arr.ndim)   # 배열 차원의 수
print("shape: ", arr.shape) # 배열 각 차원의 크기를 튜플 형태로 반환
print("size: ", arr.size)   # 배열 원소의 갯수
print("dtype: ", arr.dtype) # 배열 내 원소의 데이터형
print("itemsize: ", arr.itemsize)   # 배열 내 원소의 크기를 바이트 단위로 반환
print("nbytes: ", arr.nbytes)   # 배열의 전체 바이트(size * itemsize)

[1 2 3 4 5]
ndim:  1
shape:  (5,)
size:  5
dtype:  int32
itemsize:  4
nbytes:  20


In [9]:
# 1차원 배열 인덱싱
a1 = np.arange(10)
print(a1)
print(a1[0])
print(a1[1])
a1[0] = 100
print(a1)

[0 1 2 3 4 5 6 7 8 9]
0
1
[100   1   2   3   4   5   6   7   8   9]


In [10]:
# 2차원 배열 인덱싱
a2 = np.arange(16).reshape(4, 4)
print(a2)
print(a2[0, 1])
print(a2[:, 1]) # 모든 행의 인덱스 1 열
print(a2[:, 1:3])   # 모든 행의 인덱스 1이상 3미만 열
print(a2[:2, 1:3])  # 인덱스 2 미만 행의 인덱스 1이상 3미만 열
print(a2[:, :-1:2]) # 모든 행의 스텝 2의 인덱스 -1미만 열
print(a2[:, ::-1]) # 모든 행의 스텝 -1의 모든 열
print(a2[:, ::-2]) # 모든 행의 스텝 -2의 모든 열


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
1
[ 1  5  9 13]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[1 2]
 [5 6]]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
[[ 3  1]
 [ 7  5]
 [11  9]
 [15 13]]


In [ ]:
a = np.arange(1, 6)
print(a)
b = [True, False, True, False, True]
print(a[b]) # a[[0, 2, 4]]랑 같음

[1 2 3 4 5]
[1 3 5]


In [ ]:
# 값 인덱싱
a = np.arange(11)
print(a)
print(a[a>5])
print(a[a%2==0])
print(a[(a>5)&(a<10)])   # and나 or 조건식을 배열에 쓸때는 항상 괄호로 묶어줘야 함
print(a[(a<5)|(a>9)])
print(a[~(a<5)])    # not

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10]
[ 0  2  4  6  8 10]
[6 7 8 9]
[ 0  1  2  3  4 10]
[ 5  6  7  8  9 10]


In [28]:
a = np.arange(1, 10)
b = np.arange(11, 20)
print(a+b)
print(a-b)
print(a*b)
print(b/a)
print(b//a) # 정수값만 반환
print(a**3) # 3제곱 값을 반환
print(np.sqrt(a))   # 제곱근

[12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171]
[11.          6.          4.33333333  3.5         3.          2.66666667
  2.42857143  2.25        2.11111111]
[11  6  4  3  3  2  2  2  2]
[  1   8  27  64 125 216 343 512 729]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [ ]:
a = np.arange(1, 10).reshape(3, 3)
print(a)
print(a.T)  # 축 바꾸기
print(a.sum())
print(a.sum(axis=0))    # 열 방향으로 계산한 행값을 리턴
print(a.sum(axis=1))    # 행 방향으로 계산한 열값을 리턴
print(a.max())
print(a.min())
print(a.mean()) # 중앙값. np.mean(a)나 np.median(a)도 같음
print(a.std())  # 표준편차

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
45
[12 15 18]
[ 6 15 24]
9
1
5.0
2.581988897471611


In [41]:
# 브로드 캐스팅(배열의 차원이 다르면 낮은 차원을 높은 차원으로 채워넣어서 계산함)
a = np.arange(1, 10).reshape(3, 3)
print(a)
b = np.arange(1, 4)
print(b)
print(a + b)
print()

# 스칼라
a = np.arange(1, 25).reshape(4, 6)
print(a + 100)
new_arr = np.full_like(a, 100)
print(new_arr)
print(a + new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]
[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [ ]:
# 행렬의 곱
a = np.arange(1, 7).reshape(2, 3)
b = a.T
print(a)
print(b)    # 행렬의 shape이 안맞춰져서 행렬곱이 안됨
print(a.dot(b)) # 앞 행렬의 열의 갯수와 뒷 행렬의 행의 갯수가 같아야만 함(반환값: (앞 행렬의 행 갯수, 뒷 행렬 열 갯수))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]


In [49]:
# 배열 형태 변경... ravel함수를 쓴다고 하는데 사실 reshape을 더 많이 씀
# 대신 reshape은 크기를 넣어줘야함 ravel은 아묻따 1차원 변경
a = np.arange(1, 7).reshape(2, 3)
a = a.reshape(6)
print(a)

b = np.arange(1, 7).reshape(2, 3).T
b1 = b.ravel()
print(b1)


[1 2 3 4 5 6]
[1 4 2 5 3 6]


In [51]:
# resize
a = np.arange(1, 10)
print(a)
b = np.resize(a, (3, 3))
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
# 요소 추가
a = np.arange(1, 10)
print(a)
b = np.append(a, 10)
print(b)
c = np.append(a, [10, 11, 12])
print(c)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# 2차원 요소 추가
a = np.arange(1, 10).reshape(3, 3)
print(a)
b = np.append(a, [[10, 11, 12]], axis=0)    # 행 추가
print(b)
c = np.append(a, [[10], [11], [12]], axis=1)    # 열 추가
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [66]:
# insert랑 append의 차이점
a = np.arange(1, 10).reshape(3, 3)
print(a)
c = np.insert(a, 1, 100)    # a를 아묻따 1차원으로 만들어서 인덱스 1 자리에 100을 집어넣음
print(c)
d = np.insert(a, 1, 100, axis=0)    # 인덱스 1의 행에 full(100)을 삽입
print(d)
e = np.insert(a, 1, 100, axis=1)    # 인덱스 1의 열에 full(100)을 삽입
print(e)
f = np.insert(a, 1, [11, 12, 13], axis=0)    # 값을 직접 넣을 수도 있음
print(f)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[  1 100   2   3   4   5   6   7   8   9]
[[  1   2   3]
 [100 100 100]
 [  4   5   6]
 [  7   8   9]]
[[  1 100   2   3]
 [  4 100   5   6]
 [  7 100   8   9]]
[[ 1  2  3]
 [11 12 13]
 [ 4  5  6]
 [ 7  8  9]]


In [69]:
# delete
b = np.delete(a, 1, axis=1) # 인덱스 1의 열 삭제
print(b)

[[1 3]
 [4 6]
 [7 9]]


In [75]:
# 배열 결합
a = np.arange(1, 6)
b = np.arange(6, 11)
print(a)
print(b)
c = np.concatenate((a, b))  # 1차원 배열은 아묻따 앞에서 뒤로 쭈욱 연결
print(c)
print()

a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
c = np.concatenate((a, b))  # 2차원 배열은 axis=0일때 아래로 붙이고 axis=1일때 옆으로 붙임
d = np.concatenate((a, b), axis=1)
print(a)
print(b)
print(c)
print(d)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [79]:
# 배열 분리
a = np.arange(1, 17).reshape(4, 4)
print(a)
b = np.hsplit(a, 2) # horizontal split
print(b)
c = np.vsplit(a, 2) # vertical split
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
